name: Build Ubuntu Rootfs Img

on:
  workflow_dispatch:
    inputs:
      ubuntu_version:
        description: 'Ubuntu version (noble or jammy)'
        required: true
        default: 'noble'
        type: choice
        options:
          - noble
          - jammy
      packages:
        description: 'Custom packages to install (comma-separated)'
        required: false
        default: ''
      image_size_mb:
        description: 'Image size in MB'
        required: true
        default: '1024'

jobs:
  build-rootfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y debootstrap kpartx qemu-user-static binfmt-support

      - name: Create base rootfs
        run: |
          sudo debootstrap --arch=amd64 ${{ github.event.inputs.ubuntu_version }} rootfs http://archive.ubuntu.com/ubuntu/

      - name: Customize rootfs
        if: github.event.inputs.packages != ''
        run: |
          sudo cp /etc/resolv.conf rootfs/etc/resolv.conf
          sudo chroot rootfs /bin/bash -c "apt-get update && apt-get install -y ${{ github.event.inputs.packages }}"

      - name: Create ext4 image
        run: |
          IMAGE_SIZE=${{ github.event.inputs.image_size_mb }}M
          sudo dd if=/dev/zero of=rootfs.img bs=1M count=${{ github.event.inputs.image_size_mb }}
          sudo mkfs.ext4 -F rootfs.img
          sudo mkdir -p /mnt/rootfs
          sudo mount rootfs.img /mnt/rootfs
          sudo cp -a rootfs/. /mnt/rootfs/
          sudo umount /mnt/rootfs

      - name: Split image into 1GB parts
        run: |
          sudo split -b 1G rootfs.img rootfs_part_

      - name: Create and upload release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}_rootfs_img
          target_commitish: ${{ github.sha }}
          files: rootfs_part_*
          name: ${{ github.run_number }}_rootfs_img
          body: "Ubuntu rootfs img for ${{ github.event.inputs.ubuntu_version }} with packages: ${{ github.event.inputs.packages }}"
          draft: false
          prerelease: false
