name: Build vmlinuz & initrd
on: 
  workflow_dispatch:
    inputs: 
      kernel:
        description: linux内核分支名
jobs:
  build:
    runs-on: ubuntu-24.04
    steps: 
      - name: 获取内核源代码
        run: git clone --depth --branch ${{ github.event.inputs.kernel }} https://github.com/torvalds/linux.git .
